# Generated by Django 5.0.6 on 2024-07-01 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='studentsregistration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('HOMECONSTRUCTIONMANAGEMENT', 'homeconstructionmanagement'), ('CLIENT', 'client'), ('EXTERIORDESIGNER', 'exteriordesigner'), ('ADMIN', 'admin'), ('ARCHITECT', 'architect'), ('CONTRACTOR', 'contractor')], max_length=30),
        ),
    ]
