# Generated by Django 5.0.6 on 2024-07-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_remove_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ARCHITECT', 'architect'), ('ADMIN', 'admin'), ('EXTERIORDESIGNER', 'exteriordesigner'), ('CONTRACTOR', 'contractor'), ('HOMECONSTRUCTIONMANAGEMENT', 'homeconstruabcionmanagement'), ('CLIENT', 'client')], max_length=30),
        ),
    ]
