# Generated by Django 5.0.6 on 2024-07-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('SALESMAN', 'SALESMAN'), ('ADMIN', 'admin'), ('CLIENT', 'client'), ('STUDENT', 'STUDENT')], max_length=30),
        ),
    ]
