# Generated by Django 5.0.6 on 2024-07-01 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsalesman',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('STUDENT', 'STUDENT'), ('SALESMAN', 'SALESMAN'), ('CLIENT', 'client')], max_length=30),
        ),
    ]
